### ISSUE TITLE
Parameter not Set

### ISSUE THREAD

**Issue by TravisH84** [rany2/warp.sh#11]
Good afternoon,

Any idea what I might be doing wrong, I am trying to run the script with a cloudflare teams token, but if I run it though ./warp.sh -T TOKEN then I get ./warp.sh: 191 ./warp.sh: Token: Parameter not set.

I tried using bash, and I get warp.sh: line 191: token: unbound variable.

I have tried with and without ' and " around the token and it makes no difference.

Many thanks!

**Comment by rany2** [comment]
Thanks for reporting the issue, I've fixed it in https://github.com/rany2/warp.sh/commit/9abcd084e427fd5c37bf0dc652e6f7f97b164526. From the commit message:

> When fixing the bug with token not being set in the WG config when using
> the newly added refresh config feature, I accidently introduces this bug.
> Fix it by initalizing the variable.
