### ISSUE TITLE
Teams: The requested URL returned error: 401

### ISSUE THREAD

**Issue by open5443** [rany2/warp.sh#14]
Hi,

after following the steps to get the token for Teams/Zero Trust and running
$ ./warp.sh -T eyJhbGciOiJSUzI1NiIsImtp[...]xVJuy6NQ7mA

the folowing error is consistently output:
curl: (22) The requested URL returned error: 401 

Is there something missing?

**Comment by mikaeldui** [comment]
I'm assuming you're using Zero Trust/Teams. You just have to be quicker. The token expires after a few minutes.

Note the changed button in the screenshot:
![image](https://github.com/user-attachments/assets/8796a26d-76f1-4c7f-8cd7-7168768ed957)

**Comment by open5443** [comment]
Hey mikaeldui,

being too slow was indeed the issue.
It seems the token is only valid for around a minute or so.

Not sure if others also sometimes counter this, but might be worth mentioning in the readme, just in case.

Thank you 🙏
