### ISSUE TITLE
Is it possible to get all possible keys and values saved when generating wireguard config files?

### ISSUE THREAD

**Issue by showgood163** [rany2/warp.sh#4]
Client ID and Reserved can be useful in some authentication situations.

**Comment by rany2** [comment]
It is possible but why?

**Comment by showgood163** [comment]
Cloudflare servers are distributed across different colocations.
Servers in different colocations require different credentials for authentication, some of which require a client id as part of credentials.

**Comment by rany2** [comment]
Could you confirm that this does what you want now?
