### ISSUE TITLE
Nothing happens when I execute the script

### ISSUE THREAD

**Issue by Doug411** [rany2/warp.sh#6]
When I execute the script, I get a command prompt  ">" and nothing happens.  To get back to my shell I have to hit CNTRL C.

**Comment by rany2** [comment]
Are you using Debian?

**Comment by Doug411** [comment]
Yes. Debian Bullseye Arm64 (Raspberry pi 4).   I also tried on AMD64 with my chromebook.

**Comment by rany2** [comment]
How are you running it? Are you pasting the script?

**Comment by Doug411** [comment]
just like your wiki suggests....

I followed the instructions to get my token.   I cloned the script.  I made sure it had execute permissions.  From the same folder I executed the command and replaced the example token with my token...

./warp.sh -T eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

**Comment by rany2** [comment]
@Doug411 what if you prepend bash to `./warp.sh`?

**Comment by Doug411** [comment]
interesting.... good idea... let me give it a go!

**Comment by rany2** [comment]
if it doesn't work, can you please run the script with `sh -x` so I could see where this is happening?

**Comment by Doug411** [comment]
We're getting somewhere!   I got a response.....[ ](curl: (22) The requested URL returned error: 401)

**Comment by rany2** [comment]
@Doug411 that means the token is too old, you need to get a new token.

**Comment by Doug411** [comment]
wait.  i think i missed the last charachter.  Trying again...

**Comment by Doug411** [comment]
Same as before I'm getting a prompt.  Like im inside bash... It doesnt return me back to my linux shell.  I have to break out of it.

**Comment by Doug411** [comment]
Interesting though.  I hadnt tried putting in an incorrect token.  The first time I tried with an incorrect token it finished and returned me back with an an error code..

**Comment by rany2** [comment]
Can't reproduce on debian 9 either, it's a bit weird...

**Comment by Doug411** [comment]
it finishes if i try without the token just sudo bash ./warp.sh,  It prints out a profile on the screen.  Is it supposed to create a file, or just print one out?

**Comment by rany2** [comment]
it's supposed to print it out, optionally you could pipe it to a file.

**Comment by Doug411** [comment]
So.... of all things my token ends with the quote charachter "

**Comment by Doug411** [comment]
The first time I tried with you I mistakenly left out the quote and it processed with an error code.  I tried again and got an error code.  Can you try replacing your last charachter with a quote?

**Comment by Doug411** [comment]
i just saw your ask about -x.   What is the full command you want me to run Is it  bash warp.sh -x -T aadjfkasjdfalkjf

**Comment by rany2** [comment]
Are you doing something like `./warp.sh -T some_token"` (with that quote at the end?)

**Comment by Doug411** [comment]
Well that was really dumb....   :)   I pasted the element into an email to crop the token.   The token appeared on a separate, independent line.  There was no starting quote after the = sign, so i guess I thought the whole thing was the string (which was odd).  Now I look at the entire header, and I can see the quote is closing out above token.

So one step forward.  It produced a profile.  I copied it into a text file and attached in WG.   It is rapidly doing a handshake and reporting that it received a response.  No internet access.  Is there something else I need to change before using the profile?

Thanks for you patience!  I appreciate your help!

**Comment by rany2** [comment]
There shouldn't be, though you might have to disconnect and reconnect the interface to get internet access. Once you get internet access it should work permanently from there and you won't need to do such a thing again.

**Comment by Doug411** [comment]
Hi again.   Just wanted to provide an update.  I finally got it working.  I was attempting it on a chromebook and an android phone.   Just an FYI, I had to remove the CIDR suffix from the local IP addresses (both IPV4 and IPV6).  Once I did that, it connected right away and has been rock solid!

**Comment by rany2** [comment]
So you simply didn't specify /32 and /128?

**Comment by rany2** [comment]
It's weird because those are the default suffixes anyway. So I'm not sure why being explicit about them would make a difference and causes it to not work. Either way, I don't see any harm in doing this, it's just strange that it was needed in your case.
